from __future__ import annotations

from tests.support.operator_commands import (
    test_health_prints_risk_snapshot_for_operator_visibility,
    test_health_reports_order_rule_fallback_risk_when_autosync_degrades,
    test_risk_report_prints_recent_evaluation_with_provenance,
    test_health_surfaces_supported_buy_price_none_resolution,
    test_health_surfaces_blocked_buy_price_none_resolution,
    test_health_summary_shows_paused_state,
    test_health_includes_balance_source_diagnostics,
    test_health_prints_accounts_preflight_outcome_context,
    test_health_summary_flags_unresolved_orders_as_resume_unsafe,
    test_runtime_readiness_is_consistent_across_reports_for_authority_gap,
    test_restart_checklist_blocks_when_restart_risks_exist,
    test_evaluate_restart_readiness_uses_lot_native_dust_authority,
    test_restart_checklist_passes_when_safe_to_resume,
    test_restart_checklist_scopes_safe_to_resume_when_sub_min_tracked_dust_allows_entry,
    test_audit_fails_on_terminal_order_with_pending_local_intent_state,
    test_repair_plan_preview_is_non_mutating_and_lists_accounting_candidates,
    test_repair_plan_help_declares_read_only_non_mutating_preview,
    test_repair_plan_preview_surfaces_position_management_mode_when_accounting_is_reliable,
)
